export const DATABASE_ID = import.meta.env.VITE_APPWRITE_DATABASE_ID;
export const COLLECTION_ID_CATEGORIES = import.meta.env.VITE_APPWRITE_COLLECTION_ID_CATEGORIES;
export const COLLECTION_ID_ACCOUNTS = import.meta.env.VITE_APPWRITE_COLLECTION_ID_ACCOUNTS;
export const COLLECTION_ID_TRANSACTIONS = import.meta.env.VITE_APPWRITE_COLLECTION_ID_TRANSACTIONS;
export const COLLECTION_ID_LOANS = import.meta.env.VITE_APPWRITE_COLLECTION_ID_LOANS;
export const COLLECTION_ID_INCOMES = import.meta.env.VITE_APPWRITE_COLLECTION_ID_INCOMES;